on: [push, pull_request]
name: Lint, test, deploy package

defaults:
  run:
    shell: bash

jobs:

  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install $(grep -E '^(black|flake8|isort|mypy)' requirements.txt)
      - run: make lint

  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10']
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          pip install -U pip wheel setuptools
          pip install -r requirements.txt
        name: Install dependencies
      - run: |
          pip install .
        name: Install package
      - run: make test-skipfull

  container:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: eWaterCycle/setup-apptainer@v2
      - run: make container

  deploy-package:
    runs-on: ubuntu-20.04
    needs: [lint, test]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install build
      - run: python -m build --sdist --wheel -o dist/ .
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
